-- Add up migration script here
CREATE TABLE IF NOT EXISTS users (
     id SERIAL PRIMARY KEY,
     username TEXT NOT NULL UNIQUE,
     created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS equities (
    id STRING PRIMARY KEY,
    ticker STRING,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS equity_prices (
    id STRING PRIMARY KEY,
    equity_id STRING,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS equity_option (
    id STRING PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS equity_option_prices (
    id STRING PRIMARY KEY,
    equity_option_id STRING,
    price FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


