#!/usr/bin/env bash

NAME=COLM

echo "data file stats"
cargo run --bin data-file-stats --  \
  --gain-threshold=0.08 \
  --loss-threshold=0.08 \
  --input=/run/media/peter/genetics/algotrader/data/${NAME}-train \

