#!/usr/bin/env bash
# for databento, use:
#    Nasdaq - XNAS.ITCH
#    NYSE - ARCX.PILLAR

#cargo run --bin downloader -- --dataset=XNAS.ITCH --symbols=SPY --start-time="2025-03-01 00:00:00 UTC" --end-time="2026-04-01 23:59:59 UTC"
#cargo run --bin downloader -- --dataset=XNAS.ITCH --symbols=KHC --start-time="2024-01-01 00:00:00 UTC" --end-time="2024-12-31 23:59:59 UTC"

cargo run --bin downloader -- --dataset=XNAS.ITCH --symbols=COLM --start-time="2025-01-01 00:00:00 UTC" --end-time="2025-12-31 23:59:59 UTC"
