#!/usr/bin/env bash

# note that positional-max-timescale can be the sequence length * 2 (i.e. 128/4*2) == 64
cargo run --bin extractor --  \
  --prediction-intervals=128 \
  --patch-intervals=8 --patch-stride=8 \
  --gain-percentage=0.1 --loss-percentage=0.1 \
  --positional-max-timescale=64 \
  --lob-levels=20 --pretty \
  --start-date=2024-12-02 --end-date=2024-12-02 \
  --output-csv=/run/media/peter/genetics/algotrader/data/KHC-train.csv \
  --output-spec=/run/media/peter/genetics/algotrader/data/KHC-spec.json \
  --extraction-interval-nanos=200000000 \
  --holding-time-seconds=5 \
  'KHC-XNAS.ITCH-2024-01-01 00:00:00 UTC-2024-12-31 23:59:59 UTC-mbo.dbn.zst'

