#!/usr/bin/env bash
#cargo run --bin historical-book -- --symbols=GOOG,GOOGL --start-time="2024-04-03T08:00:00Z" --end-time="2024-04-03T14:00:00Z"
#cargo run --bin historical-book -- --dataset=ARCX.PILLAR --symbols=WSO --start-time="2026-05-12 00:00:00 UTC" --end-time="2026-05-12 23:59:59 UTC"


# Verisign
#cargo run --bin historical-book -- --dataset=XNAS.ITCH --symbols=VRSN --start-time="2026-05-04 00:00:00 UTC" --end-time="2026-05-04 23:59:59 UTC"
#cargo run --bin historical-book -- --dataset=XNAS.ITCH --symbols=VRSN --start-time="2026-05-12 00:00:00 UTC" --end-time="2026-05-12 23:59:59 UTC"

# Lennar Corp
#cargo run --bin historical-book -- --dataset=ARCX.PILLAR --symbols=LEN --start-time="2026-05-12 00:00:00 UTC" --end-time="2026-05-12 23:59:59 UTC"


# Apple
#cargo run --bin historical-book -- --dataset=XNAS.ITCH --symbols=AAPL --start-time="2026-05-04 00:00:00 UTC" --end-time="2026-05-04 23:59:59 UTC"


# NFLX
#cargo run --bin historical-book -- --dataset=XNAS.ITCH --symbols=NFLX --start-time="2026-05-04 00:00:00 UTC" --end-time="2026-05-04 23:59:59 UTC"


# Kraft-Heinz
#cargo run --bin historical-book -- --dataset=XNAS.ITCH --symbols=KHC --start-time="2026-05-04 00:00:00 UTC" --end-time="2026-05-04 23:59:59 UTC"

cargo run --bin downloader -- --dataset=XNAS.ITCH --symbols=KHC --start-time="2026-05-05 00:00:00 UTC" --end-time="2026-05-05 23:59:59 UTC"
#cargo run --bin historical-book -- --dataset=XNAS.ITCH --symbols=KHC --start-time="2026-05-05 00:00:00 UTC" --end-time="2026-05-05 23:59:59 UTC"
