#!/usr/bin/env bash
#cargo run --bin order-book -- --symbols=GOOG,GOOGL --start-time="2024-04-03 08:00:00 UTC" --end-time="2024-04-03 14:00:00 UTC"
#cargo run --bin order-book -- --symbols=DVLT --start-time="2024-04-03T08:00:00Z" --end-time="2024-04-03T14:00:00Z"
cargo run --bin order-book -- --symbols=WSO --start-time="2024-04-03T08:00:00Z" --end-time="2024-04-03T14:00:00Z"

