#!/usr/bin/env bash

NAME=KHC
cargo run --bin shuffle-data-file --  \
  --seed=42 \
  --input=/run/media/peter/genetics/algotrader/data/${NAME}-train \
  --output=/run/media/peter/genetics/algotrader/data/${NAME}-train-shuffled

