#!/usr/bin/env bash

#NAME=KHC
NAME=COLM

#
# Originally we started with 8 heads and 4 layers
# export CUBECL_AUTOTUNE_LEVEL=0
# output-feed-forward-size should be 4x token size
#
cargo run --bin train -- \
  --spec-file=${NAME}-spec.json \
  --dataset-file=${NAME}-train-shuffled \
  --batch-size=64 \
  --num-epochs=5 \
  --dropout=0.1 \
  --shuffle-seed=42 \
  --transformer-heads=8 \
  --transformer-layers=4 \
  --output-feed-forward-size=1312 \
  --loss-weights=51.976,0.338,52.173 \
  --gain-threshold=0.08 \
  --loss-threshold=0.08 \
  --artifacts-folder=/run/media/peter/genetics/algotrader/data/${NAME}-artifacts






