#!/usr/bin/env bash

NAME=KHC
#NAME=COLM

#
# Originally we started with 8 heads and 4 layers
# export CUBECL_AUTOTUNE_LEVEL=0
# output-feed-forward-size should be 4x token size
#
cargo run --bin train -- \
  --spec-file=${NAME}-spec.json \
  --dataset-file=${NAME}-train-shuffled \
  --batch-size=64 \
  --num-epochs=2 \
  --dropout=0.1 \
  --shuffle-seed=42 \
  --transformer-heads=4 \
  --transformer-layers=2 \
  --loss-weights=652.167,0.334,484.718 \
  --gain-threshold=0.08 \
  --loss-threshold=0.08 \
  --artifacts-folder=/run/media/peter/genetics/algotrader/data/${NAME}-artifacts

# KHC
#Total samples: 215215
#Absolute => Gains: (148).  Neutrals (214957).  Losses (110)
#Percentage => Gains: (0.069%).  Neutrals (99.880%).  Losses (0.051%)
#Inverse Frequency Weights Matrix: [652.167,0.334,484.718]
#Simplified Inverse Frequency Weights Matrix: [1956.500,1.001,1454.155]
#Log Scaled Ln - Inverse Frequency Weights Matrix: [7.579,0.694,7.283]
#Log Scaled Log10 - Inverse Frequency Weights Matrix: [2.096,1.661,2.095]